Repository dislocated-su/ENG1-2, pull requests merged in 2023-05, with the labels that each got.

#106 StationActionTests
  tests/src/cs/eng1/tests/StationActionTests.java
Labels: testing

#109 Chef Purchasing, CustomerManager and UI Update
  assets/e.tmx
  assets/piazza-panic.tiled-session
  core/src/cs/eng1/piazzapanic/PiazzaPanicGame.java
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/box2d/Box2dRaycastCollisionDetector.java
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  core/src/cs/eng1/piazzapanic/customer/Customer.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicChoppable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicCookable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicGrillable.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/stations/StationCollider.java
  core/src/cs/eng1/piazzapanic/stations/SubmitStation.java
  core/src/cs/eng1/piazzapanic/ui/FontManager.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UIStopwatch.java
  core/src/cs/eng1/piazzapanic/ui/UpgradesUi.java
  core/src/cs/eng1/piazzapanic/utility/Timer.java
Labels: enhancement

#108 Box2d tests
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  tests/src/cs/eng1/tests/ChefManagerTests.java
  tests/src/cs/eng1/tests/ChefTests.java
  tests/src/cs/eng1/tests/CustomerManagerTests.java
  tests/src/cs/eng1/tests/IngredientTests.java
  tests/src/cs/eng1/tests/StationColliderTests.java
  tests/src/cs/eng1/tests/SubmitStationTests.java
  tests/src/cs/eng1/tests/box2d/MapBodyBuilderTests.java
  tests/src/cs/eng1/tests/box2d/box2dLocationTests.java
  tests/src/cs/eng1/tests/box2d/box2dSteeringBodyTests.java
Labels: testing

#112 Organise Test Files
  tests/src/cs/eng1/tests/assets/AssetTests.java
  tests/src/cs/eng1/tests/chef/ChefManagerTests.java
  tests/src/cs/eng1/tests/chef/ChefTests.java
  tests/src/cs/eng1/tests/chef/FixedStackTests.java
  tests/src/cs/eng1/tests/customer/CustomerManagerTests.java
  tests/src/cs/eng1/tests/food/ingredients/BasicChoppableTests.java
  tests/src/cs/eng1/tests/food/ingredients/BasicCookableTests.java
  tests/src/cs/eng1/tests/food/ingredients/BasicGrillableTests.java
  tests/src/cs/eng1/tests/food/ingredients/IngredientTests.java
  tests/src/cs/eng1/tests/food/recipes/RecipeTests.java
  tests/src/cs/eng1/tests/stations/ChoppingStationTests.java
  tests/src/cs/eng1/tests/stations/CookingStationTests.java
  tests/src/cs/eng1/tests/stations/GrillingStationTests.java
  tests/src/cs/eng1/tests/stations/IngredientStationTests.java
  tests/src/cs/eng1/tests/stations/RecipeStationTests.java
  tests/src/cs/eng1/tests/stations/StationActionTests.java
  tests/src/cs/eng1/tests/stations/StationColliderTests.java
  tests/src/cs/eng1/tests/stations/StationTests.java
  tests/src/cs/eng1/tests/stations/SubmitStationTests.java
  tests/src/cs/eng1/tests/utility/KeyboardInputTests.java
Labels: enhancement

#117 Add end screen, fix scenario mode
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/screens/EndScreen.java
  core/src/cs/eng1/piazzapanic/screens/HomeScreen.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UpgradesUi.java
Labels: enhancement

#114 Improvements to customers
  core/src/cs/eng1/piazzapanic/customer/Customer.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
Labels: bug, enhancement

#120 Saving
  .gitignore
  assets/food/original/burnt.png
  assets/food/original/rotten.png
  core/src/cs/eng1/piazzapanic/PiazzaPanicGame.java
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  core/src/cs/eng1/piazzapanic/customer/Customer.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/food/FoodTextureManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicChoppable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicCookable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicGrillable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/Cheese.java
  core/src/cs/eng1/piazzapanic/food/ingredients/UncookedPizza.java
  core/src/cs/eng1/piazzapanic/food/interfaces/Holdable.java
  core/src/cs/eng1/piazzapanic/food/recipes/Recipe.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/screens/HomeScreen.java
  core/src/cs/eng1/piazzapanic/stations/IngredientStack.java
  core/src/cs/eng1/piazzapanic/stations/RecipeStation.java
  core/src/cs/eng1/piazzapanic/stations/Station.java
  core/src/cs/eng1/piazzapanic/stations/SubmitStation.java
  core/src/cs/eng1/piazzapanic/ui/PauseOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UpgradesUi.java
  core/src/cs/eng1/piazzapanic/utility/Timer.java
  core/src/cs/eng1/piazzapanic/utility/saving/SaveManager.java
  core/src/cs/eng1/piazzapanic/utility/saving/SaveState.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedChef.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedChefManager.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedCustomer.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedCustomerManager.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedFood.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedIngredientStack.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedPlayerState.java
  core/src/cs/eng1/piazzapanic/utility/saving/SavedStation.java
  core/src/cs/eng1/piazzapanic/utility/saving/SerializeableMap.java
Labels: enhancement

#122 Chef manager retest
  .gitignore
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  core/src/cs/eng1/piazzapanic/screens/HomeScreen.java
  core/src/cs/eng1/piazzapanic/utility/saving/SaveManager.java
  tests/src/cs/eng1/tests/box2d/box2dSteeringBodyTests.java
  tests/src/cs/eng1/tests/chef/ChefManagerTests.java
  tests/src/cs/eng1/tests/chef/ChefTests.java
  tests/src/cs/eng1/tests/chef/FixedStackTests.java
  tests/src/cs/eng1/tests/customer/CustomerManagerTests.java
  tests/src/cs/eng1/tests/food/ingredients/BasicCookableTests.java
  tests/src/cs/eng1/tests/food/ingredients/BasicGrillableTests.java
  tests/src/cs/eng1/tests/food/ingredients/IngredientTests.java
  tests/src/cs/eng1/tests/playerState/PlayerStateTests.java
  tests/src/cs/eng1/tests/stations/StationColliderTests.java
  tests/src/cs/eng1/tests/stations/SubmitStationTests.java
Labels: testing

#124 Create a release on a git tag
  .github/workflows/release.yml
Labels: enhancement
