Repository dislocated-su/ENG1-2, pull requests merged in 2023-04, with the labels that each got.

#70 Power Up Creation
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  core/src/cs/eng1/piazzapanic/customer/Customer.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicChoppable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicCookable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicGrillable.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/stations/SubmitStation.java
  core/src/cs/eng1/piazzapanic/utility/Timer.java
  tests/src/cs/eng1/tests/BasicGrillableTests.java
  tests/src/cs/eng1/tests/SubmitStationTests.java
Labels: enhancement

#77 Chef manager tests
  build.gradle
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  tests/src/cs/eng1/tests/ChefManagerTests.java
  tests/src/cs/eng1/tests/ChefTests.java
Labels: testing

#79 KeyboardInput tests
  core/src/cs/eng1/piazzapanic/utility/KeyboardInput.java
  tests/src/cs/eng1/tests/KeyboardInputTests.java
Labels: testing

#73 New food assets
  assets/food/buff_chef/base_pizza.png
  assets/food/buff_chef/buns.png
  assets/food/buff_chef/burger.png
  assets/food/buff_chef/butter.png
  assets/food/buff_chef/cheese.png
  assets/food/buff_chef/cooked_pizza.png
  assets/food/buff_chef/dough.png
  assets/food/buff_chef/formed_dough.png
  assets/food/buff_chef/formed_patty.png
  assets/food/buff_chef/formed_pizza.png
  assets/food/buff_chef/grated_cheese.png
  assets/food/buff_chef/grilled_patty.png
  assets/food/buff_chef/jacket_potato.png
  assets/food/buff_chef/lettuce.png
  assets/food/buff_chef/onion.png
  assets/food/buff_chef/potato.png
  assets/food/buff_chef/salad.png
  assets/food/buff_chef/sliced potato.png
  assets/food/buff_chef/sliced_lettuce.png
  assets/food/buff_chef/sliced_onion.png
  assets/food/buff_chef/sliced_tomato.png
  assets/food/buff_chef/toasted_buns.png
  assets/food/buff_chef/tomato.png
  assets/food/buff_chef/tomato_paste.png
  assets/food/buff_chef/unformed_patty.png
  assets/food/food.png
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  core/src/cs/eng1/piazzapanic/food/FoodTextureManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/Cheese.java
  core/src/cs/eng1/piazzapanic/food/recipes/Recipe.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/stations/ChoppingStation.java
  core/src/cs/eng1/piazzapanic/stations/CookingStation.java
  core/src/cs/eng1/piazzapanic/stations/GrillingStation.java
  core/src/cs/eng1/piazzapanic/stations/IngredientStation.java
  core/src/cs/eng1/piazzapanic/stations/RecipeStation.java
  core/src/cs/eng1/piazzapanic/stations/Station.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
  tests/src/cs/eng1/tests/AssetTests.java
  tests/src/cs/eng1/tests/RecipeTests.java
Labels: enhancement

#85 Map Rework
  assets/Kenney-Game-Assets-2/2D assets/Topdown Shooter (620 assets)/Tilesheet/Topdown Shooter Full 2.xml
  assets/Kenney-Game-Assets-2/2D assets/Topdown Shooter (620 assets)/Tilesheet/tilesheet_complete_2X_new.png
  assets/e.tmx
  assets/food/buff_chef/cooked_potato.png
  assets/main-game-map.tmx
  assets/piazza-panic.tiled-session
  core/src/cs/eng1/piazzapanic/chef/ChefManager.java
  core/src/cs/eng1/piazzapanic/food/FoodTextureManager.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  tests/src/cs/eng1/tests/AssetTests.java
Labels: enhancement

#86 Customer manager tests
  core/src/cs/eng1/piazzapanic/customer/Customer.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  tests/src/cs/eng1/tests/CustomerManagerTests.java
Labels: testing

#87 Unlockable Stations
  assets/e.tmx
  assets/piazza-panic.tiled-project
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/stations/ChoppingStation.java
  core/src/cs/eng1/piazzapanic/stations/CookingStation.java
  core/src/cs/eng1/piazzapanic/stations/GrillingStation.java
  core/src/cs/eng1/piazzapanic/stations/IngredientStation.java
  core/src/cs/eng1/piazzapanic/stations/RecipeStation.java
  core/src/cs/eng1/piazzapanic/stations/Station.java
  core/src/cs/eng1/piazzapanic/stations/StationAction.java
  core/src/cs/eng1/piazzapanic/stations/SubmitStation.java
  core/src/cs/eng1/piazzapanic/utility/MapLoader.java
  tests/src/cs/eng1/tests/ChoppingStationTests.java
  tests/src/cs/eng1/tests/CookingStationTests.java
  tests/src/cs/eng1/tests/GrillingStationTests.java
  tests/src/cs/eng1/tests/IngredientStationTests.java
  tests/src/cs/eng1/tests/RecipeStationTests.java
  tests/src/cs/eng1/tests/StationTests.java
  tests/src/cs/eng1/tests/SubmitStationTests.java
Labels: enhancement

#81 Implement Difficulty Modes
  core/src/cs/eng1/piazzapanic/PiazzaPanicGame.java
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicChoppable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicCookable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicGrillable.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/ui/ButtonManager.java
  core/src/cs/eng1/piazzapanic/ui/ModeSelectOverlay.java
  core/src/cs/eng1/piazzapanic/utility/Timer.java
Labels: enhancement

#98 Fix NO_REP_LOSS
  core/src/cs/eng1/piazzapanic/customer/Customer.java
Labels: bug

#104 Station collider tests
  tests/src/cs/eng1/tests/CustomerManagerTests.java
  tests/src/cs/eng1/tests/StationColliderTests.java
  tests/src/cs/eng1/tests/SubmitStationTests.java
Labels: testing

#102 Test MapBodyBuilder
  assets/test-map.tmx
  core/src/cs/eng1/piazzapanic/box2d/MapBodyBuilder.java
  core/src/cs/eng1/piazzapanic/chef/Chef.java
  tests/src/cs/eng1/tests/ChefTests.java
  tests/src/cs/eng1/tests/CustomerManagerTests.java
  tests/src/cs/eng1/tests/MapBodyBuilderTests.java
Labels: testing

#94 UI changes for upgrades and more
  assets/backgroundimage.jpg
  core/src/cs/eng1/piazzapanic/PiazzaPanicGame.java
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/customer/CustomerManager.java
  core/src/cs/eng1/piazzapanic/food/FoodTextureManager.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicChoppable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicCookable.java
  core/src/cs/eng1/piazzapanic/food/ingredients/BasicGrillable.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/ui/ModeSelectOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
  core/src/cs/eng1/piazzapanic/ui/UpgradesUi.java
  core/src/cs/eng1/piazzapanic/utility/Timer.java
Labels: enhancement

#103 Pause Function
  core/src/cs/eng1/piazzapanic/PlayerState.java
  core/src/cs/eng1/piazzapanic/screens/GameScreen.java
  core/src/cs/eng1/piazzapanic/ui/StationUIController.java
  core/src/cs/eng1/piazzapanic/ui/UIOverlay.java
Labels: enhancement
